export const GALLERY_HORIZONTAL_SCROLL_START = "top top";
export const GALLERY_HORIZONTAL_SCROLL_END_PREFIX = "+=";
export const GALLERY_HORIZONTAL_SCROLL_SCRUB = true;
export const GALLERY_HORIZONTAL_SCROLL_PIN = true;
export const GALLERY_HORIZONTAL_SCROLL_INVALIDATE_ON_REFRESH = true;
export const GALLERY_HORIZONTAL_SCROLL_EASE = "none";
export const GALLERY_HORIZONTAL_SCROLL_INITIAL_X = 0;
export const GALLERY_HORIZONTAL_SCROLL_AXIS = "x";
export const GALLERY_HORIZONTAL_SCROLL_DIRECTION_MULTIPLIER = -1;
